// All world countries with comprehensive city lists
export const COUNTRIES_CITIES = {
  Afghanistan: [
    "Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad", "Kunduz",
    "Ghazni", "Balkh", "Baghlan", "Khost", "Farah", "Taloqan", "Gardez",
    "Lashkar Gah", "Pul-e-Khumri", "Sheberghan", "Zaranj", "Aybak", "Maymana",
  ].sort(),
  Albania: [
    "Tirana", "Durrës", "Vlorë", "Shkodër", "Fier", "Korçë", "Elbasan",
    "Berat", "Lushnjë", "Pogradec", "Kavajë", "Gjirokastër", "Sarandë",
    "Lezhë", "Kukës", "Peshkopi", "Burrel", "Laç", "Përmet",
  ].sort(),
  Algeria: [
    "Algiers", "Oran", "Constantine", "Blida", "Batna", "Sétif", "Annaba",
    "Béjaïa", "Tébessa", "Sidi Bel Abbès", "Tlemcen", "Skikda", "Béchar",
    "Mostaganem", "Biskra", "Médéa", "Msila", "Ouargla", "El Oued",
    "Boumerdes", "Chlef", "Djelfa", "Jijel", "Guelma", "Khenchela",
  ].sort()  ,
  Angola: [
    "Luanda", "Huambo", "Lobito", "Benguela", "Kuito", "Malanje", "Lubango",
    "Cabinda", "Uíge", "Soyo", "Menongue", "Namibe", "Saurimo", "Sumbe",
    "Ndalatando", "Luena", "Mbanza Kongo",
  ].sort(),
  Argentina: [
    "Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "San Miguel de Tucumán",
    "Mar del Plata", "Salta", "Santa Fe", "San Juan", "Resistencia", "Santiago del Estero",
    "Corrientes", "Posadas", "Bahía Blanca", "Neuquén", "Paraná", "Formosa",
    "San Salvador de Jujuy", "Río Cuarto", "Comodoro Rivadavia", "La Rioja",
    "San Luis", "Catamarca", "Santa Rosa", "Rawson", "Río Gallegos", "Ushuaia",
  ].sort(),
  Armenia: [
    "Yerevan", "Gyumri", "Vanadzor", "Abovyan", "Vagharshapat", "Hrazdan",
    "Ijevan", "Kapan", "Gavarr", "Charentsavan", "Sevan", "Artashat",
    "Sisian", "Goris", "Yeghegnadzor", "Dilijan", "Stepanavan",
  ].sort(),
  Australia: [
    "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast",
    "Canberra", "Newcastle", "Wollongong", "Hobart", "Geelong", "Townsville",
    "Cairns", "Darwin", "Toowoomba", "Ballarat", "Bendigo", "Launceston",
    "Mackay", "Rockhampton", "Bundaberg", "Bunbury", "Hervey Bay", "Wagga Wagga",
    "Albury", "Shepparton", "Mildura", "Gladstone", "Mandurah", "Tamworth",
  ].sort(),
  Austria: [
    "Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Villach",
    "Wels", "Sankt Pölten", "Dornbirn", "Wiener Neustadt", "Steyr", "Feldkirch",
    "Bregenz", "Wolfsberg", "Baden bei Wien", "Leoben", "Krems an der Donau",
    "Traun", "Leonding", "Klosterneuburg",
  ].sort(),
  Azerbaijan: [
    "Baku", "Ganja", "Sumqayit", "Mingachevir", "Nakhchivan", "Shirvan",
    "Lankaran", "Shaki", "Yevlakh", "Khankendi", "Quba", "Qabala",
    "Zagatala", "Goychay", "Barda", "Aghjabadi", "Bilasuvar",
  ].sort(),
  Bahrain: [
    "Manama", "Riffa", "Muharraq", "Hamad Town", "Isa Town", "Sitrah",
    "Al-Malikiyah", "Jidhafs", "Tubli", "Budaiya", "Jidd Hafs", "Saar",
  ].sort(),
  Bangladesh: [
    "Dhaka", "Chittagong", "Sylhet", "Khulna", "Rajshahi", "Comilla",
    "Narayanganj", "Gazipur", "Rangpur", "Mymensingh", "Barishal", "Jessore",
    "Tongi", "Bogra", "Dinajpur", "Nawabganj", "Pabna", "Tangail",
    "Sirajganj", "Nawabganj", "Saidpur", "Jamalpur", "Feni", "Noakhali",
  ].sort(),
  Belgium: [
    "Brussels", "Antwerp", "Ghent", "Bruges", "Liège", "Leuven", "Mechelen",
    "Namur", "Hasselt", "Mons", "Louvain-la-Neuve", "Aalst", "Kortrijk",
    "Genk", "Tournai", "Ostend", "Sint-Niklaas", "Roeselare", "Mouscron",
    "Verviers", "Charleroi", "La Louvière", "Arlon", "Dinant",
  ].sort(),
  Bolivia: [
    "La Paz", "Santa Cruz", "Cochabamba", "Sucre", "Oruro", "Potosí",
    "Tarija", "Trinidad", "Cobija", "Riberalta", "Montero", "Warnes",
    "Yacuiba", "Camiri", "Llallagua", "Tupiza", "Villazón",
  ].sort(),
  "Bosnia and Herzegovina": [
    "Sarajevo", "Banja Luka", "Mostar", "Tuzla", "Zenica", "Bijeljina",
    "Prijedor", "Brčko", "Doboj", "Bihać", "Trebinje", "Foča",
    "Zvornik", "Bosanska Krupa", "Goražde",
  ].sort(),
  Brazil: [
    "São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza",
    "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Goiânia", "Porto Alegre",
    "Belém", "Guarulhos", "Campinas", "São Luís", "São Gonçalo", "Maceió",
    "Duque de Caxias", "Natal", "Teresina", "Campo Grande", "Nova Iguaçu",
    "São Bernardo do Campo", "João Pessoa", "Santo André", "Osasco",
    "Ribeirão Preto", "Uberlândia", "Contagem", "Sorocaba", "Aracaju",
    "Feira de Santana", "Cuiabá", "Joinville", "Juiz de Fora", "Londrina",
    "Niterói", "Ananindeua", "Porto Velho", "Florianópolis", "Macapá", "Boa Vista",
  ].sort(),
  Bulgaria: [
    "Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora", "Pleven",
    "Sliven", "Dobrich", "Shumen", "Pernik", "Haskovo", "Yambol", "Pazardzhik",
    "Blagoevgrad", "Lovech", "Targovishte", "Vidin", "Montana", "Kardzhali",
    "Silistra", "Gabrovo", "Smolyan", "Vratsa", "Razgrad",
  ].sort(),
  Cambodia: [
    "Phnom Penh", "Siem Reap", "Battambang", "Preah Sihanouk", "Kampong Cham",
    "Kampong Speu", "Takeo", "Kampot", "Pursat", "Kep", "Kratie",
    "Poipet", "Prey Veng", "Svay Rieng", "Stung Treng",
  ].sort(),
  Cameroon: [
    "Yaoundé", "Douala", "Bamenda", "Maroua", "Ngaoundéré", "Garoua",
    "Bafoussam", "Kumba", "Bertoua", "Buea", "Ebolowa", "Edéa", "Kribi",
    "Foumban", "Dschang", "Loum", "Nkongsamba", "Bafia",
  ].sort(),
  Canada: [
    "Toronto", "Montreal", "Vancouver", "Calgary", "Ottawa", "Edmonton",
    "Québec City", "Winnipeg", "Hamilton", "Kitchener", "London", "Victoria",
    "Halifax", "Oshawa", "Windsor", "Saskatoon", "Regina", "St. John's",
    "Barrie", "Kelowna", "Abbotsford", "Kingston", "Sudbury", "Sherbrooke",
    "Saguenay", "Trois-Rivières", "Moncton", "Fredericton", "Charlottetown",
    "Whitehorse", "Yellowknife", "Iqaluit",
  ].sort(),
  Chile: [
    "Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta",
    "Temuco", "Rancagua", "Talca", "Arica", "Iquique", "Puerto Montt",
    "Coquimbo", "Chillán", "Calama", "Los Ángeles", "Osorno", "Valdivia",
    "Punta Arenas", "Copiapó", "Curicó", "Ovalle",
  ].sort(),
  China: [
    "Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Hangzhou",
    "Tianjin", "Wuhan", "Xi'an", "Nanjing", "Chongqing", "Suzhou",
    "Qingdao", "Zhengzhou", "Dalian", "Jinan", "Shenyang", "Harbin",
    "Changsha", "Kunming", "Nanchang", "Hefei", "Fuzhou", "Xiamen",
    "Ningbo", "Dongguan", "Foshan", "Lanzhou", "Guiyang", "Taiyuan",
    "Xining", "Hohhot", "Urumqi", "Lhasa", "Nanning", "Haikou", "Sanya",
    "Shijiazhuang", "Wenzhou", "Changchun",
  ].sort(),
  Colombia: [
    "Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Bucaramanga",
    "Pereira", "Santa Marta", "Ibagué", "Manizales", "Cúcuta", "Villavicencio",
    "Bello", "Pasto", "Montería", "Neiva", "Palmira", "Armenia", "Buenaventura",
    "Valledupar", "Sincelejo", "Popayán", "Floridablanca", "Itagüí",
  ].sort(),
  "Costa Rica": [
    "San José", "Alajuela", "Cartago", "Heredia", "Liberia", "Pérez Zeledón",
    "Desamparados", "San Carlos", "Puntarenas", "Limón", "Filadelfia", "Nicoya",
    "Guápiles", "Turrialba", "Santa Cruz",
  ].sort(),
  Croatia: [
    "Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Slavonski Brod",
    "Pula", "Petrinja", "Karlovac", "Varaždin", "Šibenik", "Sisak",
    "Dubrovnik", "Bjelovar", "Koprivnica", "Vukovar", "Đakovo", "Gospić",
  ].sort(),
  Cuba: [
    "Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara",
    "Guantánamo", "Bayamo", "Las Tunas", "Ciego de Ávila", "Cienfuegos",
    "Matanzas", "Pinar del Río", "Manzanillo", "Morón", "Trinidad",
  ].sort(),
  Cyprus: [
    "Nicosia", "Limassol", "Larnaca", "Paphos", "Famagusta", "Kyrenia",
    "Paralimni", "Aradippou", "Lakatamia", "Morphou",
  ].sort(),
  Czechia: [
    "Prague", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc", "Ústí nad Labem",
    "České Budějovice", "Hradec Králové", "Pardubice", "Jihlava", "Zlín",
    "Kladno", "Most", "Opava", "Frýdek-Místek", "Karviná", "Teplice",
    "Chomutov", "Děčín", "Havířov",
  ].sort(),
  Denmark: [
    "Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers",
    "Herning", "Helsingør", "Silkeborg", "Vejle", "Horsens", "Roskilde",
    "Kolding", "Næstved", "Frederiksberg", "Guldborgsund", "Sønderborg",
    "Hvidovre", "Gladsaxe",
  ].sort(),
  "Dominican Republic": [
    "Santo Domingo", "Santiago", "La Vega", "Higüey", "San Pedro de Macorís",
    "La Romana", "San Francisco de Macorís", "Puerto Plata", "Moca", "Barahona",
    "Bonao", "San Cristóbal", "Cotui", "Constanza", "Azua",
  ].sort(),
  Ecuador: [
    "Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Manta", "Portoviejo",
    "Loja", "Ambato", "Machala", "Riobamba", "Ibarra", "Quevedo",
    "Milagro", "Esmeraldas", "Babahoyo", "Durán", "Latacunga", "Tulcán",
    "Santa Elena", "Salinas",
  ].sort(),
  Egypt: [
    "Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Luxor", "Aswan",
    "Mansoura", "Tanta", "Asyut", "Ismailia", "Faiyum", "Port Said",
    "Suez", "Damietta", "Zagazig", "Kafr el-Sheikh", "Beni Suef",
    "Minya", "Qena", "Hurghada", "Sohag", "Shibin el-Kom", "Banha",
    "Sidi Ghazi", "Sharm el-Sheikh",
  ].sort(),
  "El Salvador": [
    "San Salvador", "Santa Ana", "San Miguel", "Soyapango", "Nueva San Salvador",
    "Apopa", "Mejicanos", "Delgado", "Ahuachapán", "Usulután",
    "Cuscatancingo", "Ilopango", "Zacatecoluca", "Chalchuapa",
  ].sort(),
  Estonia: [
    "Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve", "Viljandi",
    "Rakvere", "Maardu", "Sillamäe", "Kuressaare", "Võru", "Valga",
    "Haapsalu", "Jõhvi", "Paide",
  ].sort(),
  Ethiopia: [
    "Addis Ababa", "Dire Dawa", "Gondar", "Mekelle", "Hawassa", "Bahir Dar",
    "Nazreth", "Dessie", "Jimma", "Jijiga", "Shashemene", "Bishoftu",
    "Sodo", "Arba Minch", "Hosaena", "Harar",
  ].sort(),
  Finland: [
    "Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä",
    "Lahti", "Kuopio", "Kouvola", "Pori", "Joensuu", "Lappeenranta",
    "Hämeenlinna", "Vaasa", "Seinäjoki", "Rovaniemi", "Mikkeli",
    "Kotka", "Salo", "Porvoo", "Lohja", "Hyvinkää",
  ].sort(),
  France: [
    "Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Bordeaux",
    "Montpellier", "Strasbourg", "Rennes", "Grenoble", "Toulon", "Dijon",
    "Nîmes", "Aix-en-Provence", "Reims", "Le Havre", "Saint-Étienne",
    "Angers", "Villeurbanne", "Brest", "Clermont-Ferrand", "Amiens",
    "Limoges", "Metz", "Nancy", "Perpignan", "Mulhouse", "Rouen",
    "Besançon", "Caen", "Orléans", "Valenciennes", "Pau", "Tours",
    "Poitiers", "Avignon", "Boulogne-Billancourt", "Lille",
  ].sort(),
  Georgia: [
    "Tbilisi", "Kutaisi", "Batumi", "Rustavi", "Gori", "Zugdidi",
    "Poti", "Samtredia", "Khashuri", "Zugdidi", "Telavi", "Kobuleti",
    "Chiatura", "Tsqaltubo", "Senaki",
  ].sort(),
  Germany: [
    "Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart",
    "Düsseldorf", "Leipzig", "Dortmund", "Essen", "Bremen", "Dresden",
    "Hanover", "Nuremberg", "Duisburg", "Bochum", "Wuppertal", "Bielefeld",
    "Bonn", "Münster", "Karlsruhe", "Mannheim", "Augsburg", "Wiesbaden",
    "Gelsenkirchen", "Mönchengladbach", "Braunschweig", "Chemnitz",
    "Kiel", "Aachen", "Halle", "Magdeburg", "Freiburg", "Krefeld",
    "Lübeck", "Oberhausen", "Erfurt", "Mainz", "Rostock", "Kassel",
    "Hagen", "Hamm", "Saarbrücken", "Mülheim", "Potsdam", "Ludwigshafen",
  ].sort(),
  Ghana: [
    "Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Ashaiman", "Cape Coast",
    "Tema", "Obuasi", "Teshie", "Madina", "Koforidua", "Wa", "Ho",
    "Bolgatanga", "Sunyani", "Techiman", "Berekum",
  ].sort(),
  Greece: [
    "Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos",
    "Rhodes", "Ioannina", "Agrinio", "Chalcis", "Kavala", "Serres",
    "Alexandroupoli", "Piraeus", "Katerini", "Drama", "Lamia", "Corfu",
    "Trikala", "Veria", "Kalamata",
  ].sort(),
  Guatemala: [
    "Guatemala City", "Mixco", "Villa Nueva", "Quetzaltenango", "Chinautla",
    "San Miguel Petapa", "Amatitlán", "Escuintla", "Huehuetenango",
    "Cobán", "Jalapa", "Puerto Barrios", "Chiquimula", "Retalhuleu",
    "Sololá", "Santa Lucía Cotzumalguapa",
  ].sort(),
  Honduras: [
    "Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba", "El Progreso",
    "Choluteca", "Comayagua", "Puerto Cortés", "Villanueva", "Danli",
    "Siguatepeque", "Juticalpa", "Santa Rosa de Copán",
  ].sort(),
  Hungary: [
    "Budapest", "Debrecen", "Miskolc", "Szeged", "Pécs", "Győr", "Nyíregyháza",
    "Kecskemét", "Székesfehérvár", "Szombathely", "Szolnok", "Tatabánya",
    "Kaposvár", "Eger", "Veszprém", "Zalaegerszeg", "Sopron", "Érd",
  ].sort(),
  India: [
    "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune",
    "Ahmedabad", "Surat", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Visakhapatnam",
    "Indore", "Thane", "Bhopal", "Pimpri-Chinchwad", "Patna", "Vadodara",
    "Ludhiana", "Agra", "Kalyan", "Nash", "Faridabad", "Meerut", "Rajkot",
    "Varanasi", "Amritsar", "Navi Mumbai", "Allahabad", "Ranchi", "Howrah",
    "Coimbatore", "Jabalpur", "Gwalior", "Vijayawada", "Jodhpur", "Madurai",
    "Raipur", "Kota", "Chandigarh", "Guwahati", "Solapur", "Aurangabad",
    "Tiruchirappalli", "Mysore", "Bareilly", "Aligarh", "Moradabad", "Srinagar",
    "Jalandhar", "Bhubaneswar", "Saharanpur", "Thiruvananthapuram", "Jamshedpur",
    "Dhanbad", "Kochi", "Kozhikode", "Dehradun", "Mangalore",
  ].sort(),
  Indonesia: [
    "Jakarta", "Surabaya", "Bandung", "Medan", "Semarang", "Makassar",
    "Palembang", "Tangerang", "Depok", "Bekasi", "South Tangerang",
    "Batam", "Pekanbaru", "Bandar Lampung", "Padang", "Malang",
    "Samarinda", "Bogor", "Balikpapan", "Pontianak", "Denpasar",
    "Yogyakarta", "Banjarmasin", "Jambi", "Manado", "Mataram",
    "Kupang", "Ambon", "Jayapura", "Palangkaraya",
  ].sort(),
  Iran: [
    "Tehran", "Mashhad", "Isfahan", "Karaj", "Tabriz", "Shiraz",
    "Ahvaz", "Qom", "Kermanshah", "Rasht", "Zahedan", "Hamadan",
    "Arak", "Urmia", "Yazd", "Kerman", "Ardabil", "Bandar Abbas",
    "Zanjan", "Sanandaj", "Birjand", "Khorramabad", "Semnan",
    "Qazvin", "Gorgan", "Dezful",
  ].sort(),
  Iraq: [
    "Baghdad", "Basra", "Mosul", "Erbil", "Najaf", "Karbala", "Kirkuk",
    "Sulaymaniyah", "Nasiriyah", "Ramadi", "Baquba", "Faluja", "Hillah",
    "Tikrit", "Dohuk", "Kut", "Samarra",
  ].sort(),
  Ireland: [
    "Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda",
    "Dundalk", "Swords", "Bray", "Navan", "Kilkenny", "Ennis",
    "Sligo", "Tralee", "Newbridge", "Portlaoise", "Balbriggan",
    "Naas", "Carlow", "Mullingar", "Athlone",
  ].sort(),
  Israel: [
    "Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva",
    "Ashdod", "Netanya", "Beersheba", "Bnei Brak", "Bat Yam",
    "Holon", "Ramat Gan", "Ashkelon", "Rehovot", "Herzliya",
    "Kfar Saba", "Lod", "Modi'in", "Nazareth", "Acre",
  ].sort(),
  Italy: [
    "Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna",
    "Florence", "Venice", "Bari", "Messina", "Catania", "Verona",
    "Trieste", "Padua", "Brescia", "Prato", "Reggio Calabria", "Modena",
    "Reggio Emilia", "Perugia", "Livorno", "Ravenna", "Cagliari",
    "Foggia", "Rimini", "Salerno", "Ferrara", "Sassari", "Latina",
    "Siracusa", "Bergamo", "Taranto", "Monza", "Trento", "Bolzano",
    "Ancona", "La Spezia", "Arezzo", "Udine",
  ].sort(),
  "Ivory Coast": [
    "Abidjan", "Bouaké", "Daloa", "Yamoussoukro", "Korhogo", "San-Pédro",
    "Divo", "Gagnoa", "Abobo", "Man", "Soubré", "Anyama", "Duekoué",
  ].sort(),
  Jamaica: [
    "Kingston", "Spanish Town", "Portmore", "Montego Bay", "Mandeville",
    "May Pen", "Halfwa Tree", "Old Harbour", "Linstead",
  ].sort(),
  Japan: [
    "Tokyo", "Osaka", "Yokohama", "Nagoya", "Sapporo", "Kyoto", "Fukuoka",
    "Kobe", "Kawasaki", "Saitama", "Hiroshima", "Sendai", "Kitakyushu",
    "Chiba", "Sakai", "Niigata", "Hamamatsu", "Okayama", "Sagamihara",
    "Kumamoto", "Shizuoka", "Matsuyama", "Utsunomiya", "Matsudo",
    "Nara", "Nishinomiya", "Kanazawa", "Oita", "Nagasaki", "Kagoshima",
    "Funahashi", "Suita", "Toyama", "Nagano", "Matsumoto", "Takamatsu",
  ].sort(),
  Jordan: [
    "Amman", "Zarqa", "Irbid", "Aqaba", "Russeifa", "Wadi Al-Seer",
    "Sahab", "Al-Quwaysmah", "Khuraybah", "Madaba", "Jerash",
    "Ajloun", "Karak", "Ma'an", "Tafilah",
  ].sort(),
  Kazakhstan: [
    "Almaty", "Nur-Sultan", "Shymkent", "Karaganda", "Aktobe", "Taraz",
    "Pavlodar", "Ust-Kamenogorsk", "Semey", "Atyrau", "Kostanay",
    "Kyzylorda", "Uralsk", "Petropavl", "Temirtau", "Aktau",
    "Taldykorgan", "Ekibastuz",
  ].sort(),
  Kenya: [
    "Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika",
    "Malindi", "Kitale", "Machakos", "Embu", "Nyeri", "Meru",
    "Kakamega", "Garissa", "Busia", "Kericho",
  ].sort(),
  "South Korea": [
    "Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Ulsan",
    "Suwon", "Changwon", "Goyang", "Yongin", "Seongnam", "Bucheon",
    "Cheongju", "Ansan", "Jeonju", "Anyang", "Cheonan", "Namyangju",
    "Hwaseong", "Gimhae", "Pohang", "Uijeongbu",
  ].sort(),
  Kuwait: [
    "Kuwait City", "Hawalli", "Salmiya", "Farwaniya", "Jahra", "Sabah Al-Salem",
    "Ahmadi", "Fahaheel", "Mangaf", "Rumaithiyya", "Fintas",
  ].sort(),
  Laos: [
    "Vientiane", "Luang Prabang", "Savannakhet", "Pakse", "Thakhek",
    "Xam Neua", "Ban Houayxay", "Phonsavan",
  ].sort(),
  Latvia: [
    "Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala", "Ventspils",
    "Rēzekne", "Valmiera", "Jēkabpils", "Ogre",
  ].sort(),
  Lebanon: [
    "Beirut", "Tripoli", "Sidon", "Tyre", "Jounieh", "Baalbek",
    "Nabatieh", "Zahle", "Byblos", "Aley", "Batroun",
  ].sort(),
  Libya: [
    "Tripoli", "Benghazi", "Misrata", "Tarhuna", "Zawiya", "Adjusted",
    "Zliten", "Ajdabiya", "Derna", "Surt", "Al Khums", "Tobruk",
    "Sabha", "Murzuq",
  ].sort(),
  Lithuania: [
    "Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Alytus",
    "Marijampolė", "Mažeikiai", "Jonava", "Utena", "Kėdainiai",
    "Telšiai", "Visaginas",
  ].sort(),
  Luxembourg: [
    "Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange",
    "Sanem", "Bettembourg", "Petange", "Ettelbruck",
  ].sort(),
  Malaysia: [
    "Kuala Lumpur", "George Town", "Ipoh", "Shah Alam", "Petaling Jaya",
    "Johor Bahru", "Kota Kinabalu", "Kuching", "Subang Jaya", "Ampang",
    "Malacca", "Alor Setar", "Seremban", "Kuantan", "Miri", "Sibu",
    "Sandakan", "Kota Bharu", "Kuala Terengganu", "Butterworth",
  ].sort(),
  Mexico: [
    "Mexico City", "Guadalajara", "Monterrey", "Puebla", "Cancún",
    "Tijuana", "León", "Ciudad Juárez", "Mérida", "San Luis Potosí",
    "Querétaro", "Aguascalientes", "Mexicali", "Hermosillo", "Saltillo",
    "Chihuahua", "Culiacán", "Acapulco", "Morelia", "Veracruz",
    "Tlalnepantla", "Zapopan", "Torreón", "Ecatepec", "Naucalpan",
    "Tepic", "Oaxaca", "Toluca", "Durango", "Villahermosa",
    "Tuxtla Gutiérrez", "Xalapa", "Irapuato", "Mazatlán", "Matamoros",
  ].sort(),
  Moldova: [
    "Chișinău", "Tiraspol", "Bălți", "Bender", "Rîbnița", "Cahul",
    "Ungheni", "Soroca", "Orhei", "Dubăsari",
  ].sort(),
  Mongolia: [
    "Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan", "Mörön",
    "Bayankhongor", "Arvaikheer", "Ölgii", "Uliastai",
  ].sort(),
  Morocco: [
    "Casablanca", "Rabat", "Fez", "Marrakech", "Tangier", "Agadir",
    "Meknès", "Oujda", "Kenitra", "Tetouan", "Safi", "El Jadida",
    "Béni Mellal", "Khouribga", "Nador", "Khemisset", "Settat",
    "Larache", "Ksar El Kebir", "Taza", "Essaouira", "Errachidia",
  ].sort(),
  Mozambique: [
    "Maputo", "Beira", "Nampula", "Matola", "Chimoio", "Quelimane",
    "Tete", "Nacala", "Lichinga", "Pemba", "Mocuba",
  ].sort(),
  Myanmar: [
    "Yangon", "Mandalay", "Naypyidaw", "Mawlamyine", "Bago", "Pathein",
    "Sittwe", "Myeik", "Dawei", "Pyinmana", "Hpa-an", "Meiktila",
    "Lashio", "Pyay", "Sagaing",
  ].sort(),
  Nepal: [
    "Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Bharatpur",
    "Birganj", "Butwal", "Janakpur", "Siddharthanagar", "Hetauda",
    "Dharan", "Bhimsensthapur", "Itahari",
  ].sort(),
  Netherlands: [
    "Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven",
    "Groningen", "Tilburg", "Almere", "Breda", "Nijmegen",
    "Enschede", "Haarlem", "Arnhem", "Zaanstad", "Amersfoort",
    "Apeldoorn", "Dordrecht", "Leiden", "Zoetermeer", "Maastricht",
    "'s-Hertogenbosch", "Zwolle", "Delft", "Deventer",
  ].sort(),
  "New Zealand": [
    "Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga",
    "Dunedin", "Palmerston North", "Napier", "Hastings", "Nelson",
    "Rotorua", "Whangarei", "New Plymouth", "Invercargill",
  ].sort(),
  Nicaragua: [
    "Managua", "León", "Masaya", "Matagalpa", "Chinandega", "Estelí",
    "Granada", "Rivas", "Juigalpa", "Jinotega",
  ].sort(),
  Nigeria: [
    "Lagos", "Kano", "Ibadan", "Kaduna", "Abuja", "Port Harcourt",
    "Benin City", "Maiduguri", "Zaria", "Aba", "Jos", "Ilorin",
    "Oyo", "Enugu", "Abeokuta", "Onitsha", "Warri", "Sokoto",
    "Ogbomoso", "Oshogbo", "Okene", "Calabar", "Bauchi", "Akure",
    "Ado Ekiti", "Yola", "Owerri", "Uyo", "Gombe",
  ].sort(),
  Norway: [
    "Oslo", "Bergen", "Stavanger", "Trondheim", "Bærum", "Kristiansand",
    "Fredrikstad", "Drammen", "Porsgrunn", "Skien", "Sarpsborg",
    "Sandnes", "Tromsø", "Ålesund", "Tønsberg",
  ].sort(),
  Oman: [
    "Muscat", "Salalah", "Sohar", "Nizwa", "Sur", "Rustaq",
    "Ibra", "Barka", "Khasab", "Ibri", "Bahla",
  ].sort(),
  Pakistan: [
    "Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Islamabad",
    "Gujranwala", "Peshawar", "Multan", "Hyderabad", "Quetta",
    "Bahawalpur", "Sargodha", "Sialkot", "Sukkur", "Larkana",
    "Sheikhupura", "Rahim Yar Khan", "Jhang", "Mardan", "Gujrat",
    "Kasur", "Hafizabad", "Chiniot", "Kamoke", "Sadiqabad",
    "Nawabshah", "Mingora", "Mirpur Khas", "Abbottabad",
  ].sort(),
  Palestine: [
    "Gaza", "Ramallah", "Nablus", "Hebron", "Jenin", "Tulkarm",
    "Qalqilya", "Jericho", "Bethlehem", "Khan Yunis", "Rafah",
    "Deir al-Balah", "Beit Lahiya",
  ].sort(),
  Panama: [
    "Panama City", "San Miguelito", "Tocumen", "David", "Arraiján",
    "La Chorrera", "Colón", "Santiago", "Chitré", "Penonomé",
  ].sort(),
  Paraguay: [
    "Asunción", "Ciudad del Este", "Luque", "San Lorenzo", "Lambaré",
    "Fernando de la Mora", "Limpio", "Ñemby", "Encarnación",
    "Mariano Roque Alonso", "Pedro Juan Caballero",
  ].sort(),
  Peru: [
    "Lima", "Arequipa", "Trujillo", "Chiclayo", "Iquitos", "Piura",
    "Cusco", "Chimbote", "Huancayo", "Tacna", "Juliaca", "Pucallpa",
    "Ica", "Sullana", "Cajamarca", "Puno", "Ayacucho",
  ].sort(),
  Philippines: [
    "Manila", "Quezon City", "Cebu City", "Davao City", "Zamboanga City",
    "Antipolo", "Pasig", "Cagayan de Oro", "Taguig", "Valenzuela",
    "Dasmariñas", "Caloocan", "General Santos", "Las Piñas", "Makati",
    "Bacoor", "Malabon", "Lucena", "Iligan", "Muntinlupa",
    "Bacolod", "Iloilo City", "Angeles City", "Marikina",
  ].sort(),
  Poland: [
    "Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin",
    "Bydgoszcz", "Lublin", "Białystok", "Katowice", "Gdynia", "Częstochowa",
    "Radom", "Sosnowiec", "Toruń", "Kielce", "Rzeszów", "Gliwice",
    "Zabrze", "Bytom", "Bielsko-Biała", "Olsztyn", "Ruda Śląska", "Opole",
    "Tychy", "Rybnik", "Wałbrzych", "Zielona Góra", "Legnica",
  ].sort(),
  Portugal: [
    "Lisbon", "Porto", "Braga", "Coimbra", "Funchal", "Setúbal",
    "Aveiro", "Viseu", "Leiria", "Évora", "Faro", "Guimarães",
    "Valongo", "Matosinhos", "Amadora", "Almada", "Cascais", "Loures",
    "Odivelas", "Sintra", "Barreiro",
  ].sort(),
  Qatar: [
    "Doha", "Al Wakrah", "Al Khor", "Al Rayyan", "Umm Salal",
    "Al Shamal", "Al Daayen", "Lusail", "Mesaieed",
  ].sort(),
  Romania: [
    "Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța",
    "Craiova", "Brașov", "Galați", "Ploiești", "Oradea",
    "Brăila", "Arad", "Pitești", "Sibiu", "Bacău",
    "Târgu Mureș", "Baia Mare", "Buzău", "Botoșani", "Satu Mare",
    "Râmnicu Vâlcea", "Drobeta-Turnu Severin", "Suceava",
  ].sort(),
  Russia: [
    "Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan",
    "Nizhny Novgorod", "Chelyabinsk", "Omsk", "Samara", "Rostov-on-Don",
    "Ufa", "Krasnoyarsk", "Voronezh", "Perm", "Volgograd", "Krasnodar",
    "Saratov", "Tyumen", "Tolyatti", "Izhevsk", "Barnaul", "Vladivostok",
    "Irkutsk", "Khabarovsk", "Yaroslavl", "Makhachkala", "Tomsk",
    "Orenburg", "Novokuznetsk", "Kemerovo", "Astrakhan", "Ryazan",
    "Naberezhnye Chelny", "Penza", "Lipetsk", "Tula", "Kirov",
  ].sort(),
  "Saudi Arabia": [
    "Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Taif",
    "Tabuk", "Buraydah", "Khamis Mushait", "Al Hufuf",
    "Mobarraz", "Hail", "Najran", "Jizan", "Abha",
    "Al-Khobar", "Yanbu", "Al Qatif", "Arar", "Sakakah",
  ].sort(),
  Senegal: [
    "Dakar", "Touba", "Thiès", "Kaolack", "Mbour", "Saint-Louis",
    "Diourbel", "Ziguinchor", "Sédhiou", "Tambacounda", "Kolda",
  ].sort(),
  Serbia: [
    "Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica",
    "Zrenjanin", "Pančevo", "Čačak", "Novi Pazar", "Leskovac",
    "Valjevo", "Kruševac", "Vranje", "Šabac", "Smederevo",
  ].sort(),
  Singapore: ["Singapore", "Jurong East", "Woodlands", "Tampines", "Sengkang", "Punggol"].sort(),
  Slovakia: [
    "Bratislava", "Košice", "Prešov", "Žilina", "Banská Bystrica",
    "Nitra", "Trnava", "Martin", "Trenčín", "Poprad",
    "Prievidza", "Zvolen", "Považská Bystrica", "Michalovce",
  ].sort(),
  Slovenia: [
    "Ljubljana", "Maribor", "Celje", "Kranj", "Velenje",
    "Koper", "Novo Mesto", "Ptuj", "Domžale", "Nova Gorica",
  ].sort(),
  "South Africa": [
    "Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth",
    "Bloemfontein", "East London", "Pietermaritzburg", "Soweto",
    "Krugersdorp", "Benoni", "Boksburg", "Tembisa", "Germiston",
    "Upington", "Kimberley", "Polokwane", "Nelspruit", "Mahikeng",
  ].sort(),
  Spain: [
    "Madrid", "Barcelona", "Valencia", "Seville", "Bilbao", "Málaga",
    "Zaragoza", "Murcia", "Palma", "Las Palmas", "Valladolid",
    "Córdoba", "Alicante", "Vigo", "Gijón", "Hospitalet", "Coruña",
    "Granada", "Vitoria-Gasteiz", "Badalona", "Oviedo", "Cartagena",
    "Terrassa", "Jerez", "Sabadell", "Santa Cruz de Tenerife",
  ].sort(),
  "Sri Lanka": [
    "Colombo", "Kandy", "Negombo", "Galle", "Jaffna", "Batticaloa",
    "Trincomalee", "Badulla", "Ratnapura", "Kurunegala", "Anuradhapura",
    "Polonnaruwa", "Hambantota", "Matara",
  ].sort(),
  Sudan: [
    "Khartoum", "Omdurman", "Port Sudan", "Kassala", "El Obeid",
    "Wad Madani", "El Fasher", "El Geneina", "Nyala", "Atbara",
    "Gedaref", "Kosti",
  ].sort(),
  Sweden: [
    "Stockholm", "Gothenburg", "Malmö", "Uppsala", "Linköping",
    "Örebro", "Västerås", "Helsingborg", "Norrköping", "Jönköping",
    "Umeå", "Lund", "Borås", "Gävle", "Södertälje", "Eskilstuna",
    "Karlstad", "Sundsvall", "Halmstad", "Kalmar",
  ].sort(),
  Switzerland: [
    "Zürich", "Geneva", "Bern", "Basel", "Lausanne", "Winterthur",
    "St. Gallen", "Lucerne", "Lugano", "Biel/Bienne", "Thun",
    "Köniz", "La Chaux-de-Fonds", "Schaffhausen", "Fribourg",
    "Chur", "Vernier", "Neuchâtel", "Sion",
  ].sort(),
  Syria: [
    "Damascus", "Aleppo", "Homs", "Latakia", "Hama", "Deir ez-Zor",
    "Raqqa", "Hasakah", "Qamishli", "Daraa", "Tartus",
    "Ayn al-Arab", "Douma",
  ].sort(),
  Taiwan: [
    "Taipei", "New Taipei", "Taichung", "Kaohsiung", "Taoyuan",
    "Hsinchu", "Keelung", "Tainan", "Changhua", "Pingtung",
    "Zhongli", "Hualien", "Taitung",
  ].sort(),
  Tanzania: [
    "Dar es Salaam", "Mwanza", "Arusha", "Zanzibar City", "Dodoma",
    "Mbeya", "Morogoro", "Tanga", "Kahama", "Tabora",
    "Kigoma", "Lindi", "Moshi", "Musoma",
  ].sort(),
  Thailand: [
    "Bangkok", "Chiang Mai", "Pattaya", "Hat Yai", "Phuket",
    "Nonthaburi", "Pak Kret", "Udon Thani", "Chon Buri", "Nakhon Ratchasima",
    "Chiang Rai", "Ubon Ratchathani", "Khon Kaen", "Nakhon Si Thammarat",
    "Lampang", "Rayong", "Songkhla", "Surat Thani", "Phitsanulok",
  ].sort(),
  Tunisia: [
    "Tunis", "Sfax", "Sousse", "Ettadhamen", "Kairouan", "Bizerte",
    "Gabès", "Ariana", "Gafsa", "La Goulette", "Monastir",
    "Ben Arous", "Kasserine", "Béja", "Nabeul", "Médenine",
  ].sort(),
  Turkey: [
    "Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Gaziantep",
    "Konya", "Adana", "Şanlıurfa", "Diyarbakır", "Mersin", "Kayseri",
    "Eskişehir", "Trabzon", "Gebze", "Malatya", "Erzurum", "Siirt",
    "Samsun", "Denizli", "Adapazarı", "Balıkesir", "Van", "Manisa",
    "Elazığ", "Batman", "Kahramanmaraş", "Sivas",
  ].sort(),
  Ukraine: [
    "Kyiv", "Kharkiv", "Lviv", "Odessa", "Dnipro", "Donetsk",
    "Zaporizhzhia", "Lviv", "Kryvyi Rih", "Mykolaiv", "Mariupol",
    "Luhansk", "Vinnytsia", "Makiivka", "Simferopol", "Kherson",
    "Poltava", "Chernihiv", "Cherkasy", "Sumy", "Zhytomyr",
    "Ivano-Frankivsk", "Rivne", "Ternopil", "Khmelnytskyi",
    "Uzhhorod", "Lutsk",
  ].sort(),
  "United Arab Emirates": [
    "Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman",
    "Ras Al Khaimah", "Fujairah", "Umm Al Quwain",
    "Khor Fakkan", "Dibba Al-Fujairah",
  ].sort(),
  "United Kingdom": [
    "London", "Birmingham", "Manchester", "Glasgow", "Liverpool",
    "Leeds", "Sheffield", "Edinburgh", "Bristol", "Leicester",
    "Bradford", "Coventry", "Nottingham", "Kingston upon Hull",
    "Belfast", "Stoke-on-Trent", "Wolverhampton", "Plymouth",
    "Southampton", "Reading", "Derby", "Dudley", "Northampton",
    "Portsmouth", "Newcastle upon Tyne", "Sunderland", "Luton",
    "Oxford", "Cambridge", "Aberdeen", "Dundee", "Swansea", "Cardiff",
  ].sort(),
  "United States": [
    "New York", "Los Angeles", "Chicago", "Houston", "Phoenix",
    "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose",
    "Austin", "Jacksonville", "Fort Worth", "Columbus", "Indianapolis",
    "Charlotte", "San Francisco", "Seattle", "Denver", "Nashville",
    "Oklahoma City", "El Paso", "Washington D.C.", "Boston", "Las Vegas",
    "Memphis", "Louisville", "Portland", "Baltimore", "Milwaukee",
    "Albuquerque", "Tucson", "Fresno", "Sacramento", "Mesa",
    "Omaha", "Atlanta", "Colorado Springs", "Raleigh", "Virginia Beach",
    "Long Beach", "Minneapolis", "Tampa", "New Orleans", "Honolulu",
    "Detroit", "Miami", "Orlando", "Cleveland", "Pittsburgh",
    "San Bernardino", "Cincinnati", "Riverside", "Anchorage",
  ].sort(),
  Uruguay: [
    "Montevideo", "Salto", "Paysandú", "Las Piedras", "Rivera",
    "Maldonado", "Tacuarembó", "Melo", "Durazno", "San José de Mayo",
  ].sort(),
  Uzbekistan: [
    "Tashkent", "Namangan", "Samarkand", "Andijan", "Qashqadaryo",
    "Fergana", "Nukus", "Qarshi", "Bukhara", "Termez",
    "Jizzakh", "Navoiy", "Urganch", "Guliston",
  ].sort(),
  Venezuela: [
    "Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay",
    "Ciudad Guayana", "Petare", "Barcelona", "Maturín", "Cumaná",
    "Barinas", "Mérida", "San Cristóbal", "Cabimas", "Coro",
    "Punto Fijo", "Turmero", "Los Teques",
  ].sort(),
  Vietnam: [
    "Hanoi", "Ho Chi Minh City", "Da Nang", "Cần Thơ", "Hai Phong",
    "Biên Hòa", "Nha Trang", "Buôn Ma Thuột", "Huế", "Hội An",
    "Đà Lạt", "Vũng Tàu", "Thủ Dầu Một", "Rạch Giá", "Mỹ Tho",
    "Long Xuyên", "Quy Nhơn", "Nam Định",
  ].sort(),
  Yemen: [
    "Sanaa", "Aden", "Taiz", "Hodeidah", "Ibb", "Dhamar",
    "Mukalla", "Hajjah", "Saada", "Zinjibar", "Ataq",
  ].sort(),
  Zambia: [
    "Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola", "Mufulira",
    "Livingstone", "Luanshya", "Chipata", "Kasama",
  ].sort(),
  Zimbabwe: [
    "Harare", "Bulawayo", "Chitungwiza", "Mutare", "Epworth",
    "Gweru", "Kwekwe", "Kadoma", "Masvingo", "Chinhoyi",
    "Norton", "Marondera",
  ].sort(),
};

export const COUNTRY_LIST = Object.keys(COUNTRIES_CITIES).sort();
