import React from 'react';
import {
  FaWhatsapp,
  FaTelegram,
  FaDiscord,
  FaFacebook,
  FaFacebookMessenger,
  FaInstagram,
  FaReddit,
  FaSlack,
  FaSkype,
  FaLinkedin,
  FaMeetup,
  FaXTwitter,
  FaTiktok,
  FaYoutube,
  FaTwitch,
  FaSquareSnapchat,
  FaPinterest,
  FaLink,
  FaMicrosoft,
} from 'react-icons/fa6';
import {
  SiZoom,
  SiGooglemeet,
  
  SiSignal,
  SiThreads,
} from 'react-icons/si';



export const PLATFORMS = [
  {
    key: "whatsapp",
    label: "WhatsApp",
    icon: FaWhatsapp,
    color: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300 border-green-200 dark:border-green-800",
    domains: /^https?:\/\/(www\.)?(wa\.me|chat\.whatsapp\.com|api\.whatsapp\.com)(\/.*)?$/i,
    placeholder: "https://chat.whatsapp.com/...",
  },
  {
    key: "telegram",
    label: "Telegram",
    icon: FaTelegram,
    color: "bg-sky-100 text-sky-700 dark:bg-sky-900/30 dark:text-sky-300 border-sky-200 dark:border-sky-800",
    domains: /^https?:\/\/(www\.)?(t\.me|telegram\.me)(\/.*)?$/i,
    placeholder: "https://t.me/...",
  },
  {
    key: "discord",
    label: "Discord",
    icon: FaDiscord,
    color: "bg-violet-100 text-violet-700 dark:bg-violet-900/30 dark:text-violet-300 border-violet-200 dark:border-violet-800",
    domains: /^https?:\/\/(www\.)?(discord\.gg|discord\.com|discordapp\.com)(\/.*)?$/i,
    placeholder: "https://discord.gg/...",
  },
  {
    key: "zoom",
    label: "Zoom",
    icon: SiZoom,
    color: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300 border-blue-200 dark:border-blue-800",
    domains: /^https?:\/\/(www\.)?(zoom\.us|us\d+\.web\.zoom\.us)(\/.*)?$/i,
    placeholder: "https://zoom.us/j/...",
  },
  {
    key: "google_meet",
    label: "Google Meet",
    icon: SiGooglemeet,
    color: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800",
    domains: /^https?:\/\/(www\.)?(meet\.google\.com)(\/.*)?$/i,
    placeholder: "https://meet.google.com/...",
  },
  {
    key: "facebook",
    label: "Facebook",
    icon: FaFacebook,
    color: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300 border-blue-200 dark:border-blue-800",
    domains: /^https?:\/\/(www\.)?(facebook\.com|fb\.com|fb\.me|m\.facebook\.com)(\/.*)?$/i,
    placeholder: "https://facebook.com/groups/...",
  },
  {
    key: "messenger",
    label: "Messenger",
    icon: FaFacebookMessenger,
    color: "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300 border-purple-200 dark:border-purple-800",
    domains: /^https?:\/\/(www\.)?(messenger\.com|m\.me)(\/.*)?$/i,
    placeholder: "https://m.me/...",
  },
  {
    key: "instagram",
    label: "Instagram",
    icon: FaInstagram,
    color: "bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-300 border-pink-200 dark:border-pink-800",
    domains: /^https?:\/\/(www\.)?(instagram\.com|instagr\.am)(\/.*)?$/i,
    placeholder: "https://instagram.com/...",
  },
  {
    key: "reddit",
    label: "Reddit",
    icon: FaReddit,
    color: "bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-300 border-orange-200 dark:border-orange-800",
    domains: /^https?:\/\/(www\.)?(reddit\.com|old\.reddit\.com)(\/.*)?$/i,
    placeholder: "https://reddit.com/r/...",
  },
  {
    key: "slack",
    label: "Slack",
    icon: FaSlack,
    color: "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300 border-purple-200 dark:border-purple-800",
    domains: /^https?:\/\/(www\.)?([a-z0-9-]+\.)?slack\.com(\/.*)?$/i,
    placeholder: "https://yourworkspace.slack.com/...",
  },
  {
    key: "teams",
    label: "Microsoft Teams",
    icon: FaMicrosoft,
    color: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800",
    domains: /^https?:\/\/(www\.)?(teams\.microsoft\.com|teams\.live\.com)(\/.*)?$/i,
    placeholder: "https://teams.microsoft.com/...",
  },
  {
    key: "skype",
    label: "Skype",
    icon: FaSkype,
    color: "bg-sky-100 text-sky-700 dark:bg-sky-900/30 dark:text-sky-300 border-sky-200 dark:border-sky-800",
    domains: /^https?:\/\/(www\.)?(skype\.com|join\.skype\.com)(\/.*)?$/i,
    placeholder: "https://join.skype.com/...",
  },
  {
    key: "signal",
    label: "Signal",
    icon: SiSignal,
    color: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300 border-blue-200 dark:border-blue-800",
    domains: /^https?:\/\/(www\.)?(signal\.group|signal\.me)(\/.*)?$/i,
    placeholder: "https://signal.group/...",
  },
  {
    key: "linkedin",
    label: "LinkedIn",
    icon: FaLinkedin,
    color: "bg-sky-100 text-sky-700 dark:bg-sky-900/30 dark:text-sky-300 border-sky-200 dark:border-sky-800",
    domains: /^https?:\/\/(www\.)?(linkedin\.com)(\/.*)?$/i,
    placeholder: "https://linkedin.com/groups/...",
  },
  {
    key: "meetup",
    label: "Meetup",
    icon: FaMeetup,
    color: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300 border-red-200 dark:border-red-800",
    domains: /^https?:\/\/(www\.)?(meetup\.com)(\/.*)?$/i,
    placeholder: "https://meetup.com/...",
  },
  {
    key: "twitter",
    label: "X (Twitter)",
    icon: FaXTwitter,
    color: "bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300 border-gray-200 dark:border-gray-700",
    domains: /^https?:\/\/(www\.)?(twitter\.com|x\.com)(\/.*)?$/i,
    placeholder: "https://x.com/...",
  },
  {
    key: "tiktok",
    label: "TikTok",
    icon: FaTiktok,
    color: "bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300 border-gray-200 dark:border-gray-700",
    domains: /^https?:\/\/(www\.)?(tiktok\.com)(\/.*)?$/i,
    placeholder: "https://tiktok.com/@...",
  },
  {
    key: "youtube",
    label: "YouTube",
    icon: FaYoutube,
    color: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300 border-red-200 dark:border-red-800",
    domains: /^https?:\/\/(www\.)?(youtube\.com|youtu\.be)(\/.*)?$/i,
    placeholder: "https://youtube.com/...",
  },
  {
    key: "twitch",
    label: "Twitch",
    icon: FaTwitch,
    color: "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300 border-purple-200 dark:border-purple-800",
    domains: /^https?:\/\/(www\.)?(twitch\.tv)(\/.*)?$/i,
    placeholder: "https://twitch.tv/...",
  },
  {
    key: "snapchat",
    label: "Snapchat",
    icon: FaSquareSnapchat,
    color: "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-300 border-yellow-200 dark:border-yellow-800",
    domains: /^https?:\/\/(www\.)?(snapchat\.com|story\.snapchat\.com)(\/.*)?$/i,
    placeholder: "https://snapchat.com/add/...",
  },
  {
    key: "pinterest",
    label: "Pinterest",
    icon: FaPinterest,
    color: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300 border-red-200 dark:border-red-800",
    domains: /^https?:\/\/(www\.)?(pinterest\.com|pin\.it)(\/.*)?$/i,
    placeholder: "https://pinterest.com/...",
  },
  {
    key: "threads",
    label: "Threads",
    icon: SiThreads,
    color: "bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300 border-gray-200 dark:border-gray-700",
    domains: /^https?:\/\/(www\.)?(threads\.net)(\/.*)?$/i,
    placeholder: "https://threads.net/@...",
  },
];

export const PLATFORM_MAP = Object.fromEntries(
  PLATFORMS.map((p) => [p.key, p])
);

export const getPlatform = (key) =>
  PLATFORM_MAP[key] || {
    key: "unknown",
    label: "Link",
    icon: FaLink,
    color: "bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300 border-gray-200 dark:border-gray-700",
  };
